### ISSUE TITLE
Tests fail on non x86_64 machines?

### ISSUE THREAD

**Issue by johanneskastl** [NXPmicro/pypemicro#14]
I am packaging this module for openSUSE, as it is a dependency of pynitrokey.

I noticed that some of the tests fail, but only on non-x86_64 machines:

- i586
- armv7l
- s390x
- ppc64
- ppc64le
- aarch64

The tests that fail are the following:

```bash
[   16s] FAILED tests/test_basic.py::test_library_load - pypemicro.pemicro.PEMicroExce...
[   16s] FAILED tests/test_basic.py::test_lib_version - pypemicro.pemicro.PEMicroExcep...
[   16s] FAILED tests/test_basic.py::test_lib_dll_version - pypemicro.pemicro.PEMicroE...
[   16s] FAILED tests/test_basic.py::test_list_devices - pypemicro.pemicro.PEMicroExce...
[   16s] FAILED tests/test_basic.py::test_list_probes - pypemicro.pemicro.PEMicroExcep...
```

And all of them fail due to `pypemicro.pemicro.PEMicroException: There is any suitable library for this OS.`

I daresay that not many people will configure their nitro key on s390x systems, but aarch64 or ppc64 (or even i586) might be possible.

Does this module simply not work on those architectures? If so, I would try to only build it for x86_64 (where the tests succeed).

Or am I missing some other dependency?

Thanks in advance,
Johannes

**Comment by Gargy007** [comment]
Hello,
 the package is not targeted for non x86-64 machines - because is based on pre compiled libraries provided by PEMicro company. There is no way to get them for more systems - Sorry.

**Comment by johanneskastl** [comment]
> Hello, the package is not targeted for non x86-64 machines - because is based on pre compiled libraries provided by PEMicro company. There is no way to get them for more systems - Sorry.

Thanks for the reply. Then I will only build it for x86_64 machines.
