### ISSUE TITLE
Exception messages have multiple copies of prefix

### ISSUE THREAD

**Issue by flit** [NXPmicro/pypemicro#4]
When an exception is raised, the message prefix has `PEMicro Exception with error code:` added as a prefix multiple times.

When pyocd receives the exception, it ends up looking like `PEMicro Exception with error code:PEMicro Exception with error code:PEMicro Exception with error code:Unable to find any usable library in the system!`, with three copies of the prefix.

**Comment by Gargy007** [comment]
You right the rest comment has been removed in next minor version.
