### ISSUE TITLE
get_pemicro_lib() raises different error depending on get_newest

### ISSUE THREAD

**Issue by flit** [NXPmicro/pypemicro#6]
In `PyPemicro.get_pemicro_lib()`, when run on a system where no valid library is found, you will get different exceptions depending on the value of the `get_newest` parameter.

Here's the main code of `get_pemicro_lib()`:
https://github.com/NXPmicro/pypemicro/blob/806c213b13b884650cf0310ba6bb949d2ab1f0b2/pypemicro/pemicro.py#L401-L405

The branch that calls `get_newest_lib_filename()` checks whether the `libs_list` parameter is empty, and raises a specific `PEMIcroException` if so.

The other branch that calls `get_lib_filename()` doesn't check if `libs_list` is empty, and grabs index 0. So if `libs_list` is empty, you'll get an `IndexError` exception where on the newest branch you'd get a `PEMIcroException`.

**Comment by Gargy007** [comment]
The issue has been solved in version 0.1.18 :-)
